#!/usr/bin/env python3
"""Regenerate the "Available skills" table in README.md from manifest.json.

The skills table is generated, not hand-maintained: every sync runs this so the
list of skills and their descriptions can never drift from what the repo ships.
Skill names + source repos come from manifest.json; the one-line description is
the first sentence of each skill's SKILL.md frontmatter `description`.

Content is written between the BEGIN/END markers in README.md; everything else
in the file is left untouched. Run from the repo root (as scripts/sync-skill.sh
does) or anywhere — paths are resolved relative to this file.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
MANIFEST = ROOT / "manifest.json"

BEGIN = "<!-- BEGIN skills-table (generated by scripts/gen-readme.py — do not edit by hand) -->"
END = "<!-- END skills-table -->"

MAX_DESC = 95


def frontmatter_description(skill_md: Path) -> str:
    """Pull a one-line description from a SKILL.md's YAML frontmatter."""
    if not skill_md.is_file():
        return ""
    text = skill_md.read_text()
    m = re.match(r"^---\n(.*?)\n---", text, re.S)
    if not m:
        return ""
    fm = m.group(1)
    lines = fm.splitlines()
    for i, line in enumerate(lines):
        key = re.match(r"description:\s*(.*)$", line)
        if not key:
            continue
        value = key.group(1).strip()
        if value in ("|", ">", "|-", ">-", "|+", ">+"):
            # Block scalar: gather the indented lines that follow.
            block = []
            for follow in lines[i + 1:]:
                if follow.strip() == "":
                    if block:
                        break
                    continue
                if not follow.startswith((" ", "\t")):
                    break
                block.append(follow.strip())
            value = " ".join(block)
        return first_sentence(value)
    return ""


def first_sentence(text: str) -> str:
    """Lead clause, collapsed to one line, truncated, table-safe.

    Cuts at the earliest sentence-ish boundary — a period or colon followed by
    whitespace — past a short guard, so "Slack CLI for AI agents: read …" and
    "Read-only MongoDB CLI for AI agents. Use when …" both stop at the summary.
    """
    text = " ".join(text.split())
    for m in re.finditer(r"[.:]\s", text):
        if m.start() > 20:
            text = text[: m.start()]
            break
    text = text.rstrip(" .:")
    if len(text) > MAX_DESC:
        text = text[:MAX_DESC].rstrip() + "…"
    return text.replace("|", r"\|")


def build_block() -> str:
    manifest = json.loads(MANIFEST.read_text())
    names = sorted(manifest)
    rows = ["| Skill | What it does | Source |", "|---|---|---|"]
    for name in names:
        repo = manifest[name]["repo"]
        desc = frontmatter_description(ROOT / "skills" / name / "SKILL.md")
        rows.append(f"| {name} | {desc} | [{repo}](https://github.com/{repo}) |")
    count = len(names)
    return "\n".join(
        [
            BEGIN,
            "",
            f"{count} skills, synced from their source repos. See",
            "[manifest.json](manifest.json) for the authoritative list with exact",
            "versions and provenance.",
            "",
            *rows,
            "",
            END,
        ]
    )


def main() -> None:
    readme = README.read_text()
    if BEGIN not in readme or END not in readme:
        raise SystemExit("README.md is missing the skills-table markers")
    new_block = build_block()
    updated = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        lambda _: new_block,
        readme,
        count=1,
        flags=re.S,
    )
    if updated != readme:
        README.write_text(updated)
        print("gen-readme: skills table regenerated")
    else:
        print("gen-readme: skills table already current")


if __name__ == "__main__":
    main()
